# Generated by Django 4.1.1 on 2023-03-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_tag_order_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Classics', 'Classics'), ('Comic Book', 'Comic Book'), ('Fantasy', 'Fantasy'), ('spiritual', 'spiritual'), ('علوم روحية', 'علوم روحية'), (' out mind', 'out mind')], max_length=190, null=True),
        ),
    ]
