# Generated by Django 4.1.1 on 2023-03-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.ImageField(null=True, upload_to='media/pdf'),
        ),
    ]
