# Generated by Django 4.1.1 on 2023-03-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='person.png', null=True, upload_to='media/img'),
        ),
    ]
