# Generated by Django 4.1.1 on 2023-04-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0013_alter_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='preson.png', null=True, upload_to=''),
        ),
    ]
